version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres  # Use the service name of the PostgreSQL container
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Wysescale
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=c5ac49e468d664c7186a475dff7f33d29ede3f2a88aea4afb4b05d2e150f7095
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Wysescale
      - POSTGRES_DB=fastapi
    ports:
      - 5432:5432  # Expose PostgreSQL on port 5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
